merotodo-master/config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :items
  end
  

  root 'lists#index'

end

merotodo-master/app/models/item.rb
class Item < ActiveRecord::Base
	validates :content, presence: true
  belongs_to :list
end

merotodo-master/app/models/list.rb
class List < ActiveRecord::Base
	validates :title, presence:true 
	has_many :items
end

merotodo-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

merotodo-master/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @list = List.find(params[:list_id])
    @items = @list.items
  end

  def show
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])

  end

  def new
  end

  def create
    @list = List.find(params[:list_id])
    @items = @list.items.new(items_params)
    if @list.save
      redirect_to lists_path
    end  
  end

  def edit
  end

  def update
  end

  def destroy
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])
      if @item.destroy
        redirect_to(:action => :index)
      end
  end

  

  def items_params
    params.require(:item).permit(:content)
  end
end

merotodo-master/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list  = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    end
  end

  def edit
    
  end

  def update
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      redirect_to lists_path
    end
  end

  def list_params
    params.require(:list).permit(:title, :description)
  end
end

merotodo-master/app/helpers/application_helper.rb
module ApplicationHelper
end

merotodo-master/app/helpers/items_helper.rb
module ItemsHelper
end

merotodo-master/app/helpers/lists_helper.rb
module ListsHelper
end

merotodo-master/app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

merotodo-master/app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

merotodo-master/app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

merotodo-master/app/views/items/index.html.erb
<section>
	<h1>Kaam Lists</h1>
		<%@items.each do |item|%>
			<table>
				<tr>
					<td><strong>Content</strong>: </td>
					<td><%=item.content%></td>
				</tr>
				<tr>
					<td><strong>StartDate</strong>: </td>
					<td><%item.start_date%></td>
				</tr>
				<tr>
					<td><strong>FinishDate</strong>: </td>
					<td><%item.finish_date%></td>
				</tr>
			</table>
			<div id="button">
				<%= link_to "Delete", list_item_path(@list, item.id), method: :delete, data: {confirm: "Are you sure"} %>
			</div>		
		<%end%>
		<div id="button">
			<%= link_to "Back", lists_path %>
		</div>
		
</section>
		

merotodo-master/app/views/items/new.html.erb
<section>
	<h1>Items<h1/>
	<%= form_for :item, url: {:action => "create"} do |f|%>
		<table>
			<tr>
				<td><%= f.label :content%> :</td>
				<td><%= f.text_field :content%></td>
			</tr>
			<tr>
				<td><%= f.label :start_date%> :</td>
				<td><%= f.text_field :start_date, placeholder: "dd/mm/yy"%></td>
			</tr>
			<tr>
				<td><%= f.label :finish_date%> :</td>
				<td><%= f.text_field :finish_date, placeholder: "dd/mm/yy"%></td>
			</tr>
		</table>
		<%= submit_tag ("Submit")%>
	<%end%>
	<div id="button" style="margin-top: 5px;">
			<%= link_to "Back", lists_path %>
		</div>
</section>

merotodo-master/app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

merotodo-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Kaam</title>
  			<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 		 	<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrapper">
			<header>
				<div id="header_logo">
					<%= image_tag('logo.png', :size =>"50X50", :alt => 'logo') %>
				</div>
				<nav>
					<ul>
						<li><%= link_to "Home", lists_path%></li>
						<li><a href="add.html">Add Items</a></li>
						<li><a href="view.html">View Items</a></li>
					</ul>
				</nav>
			</header>
			<%= yield %>
		</div>
	</body>
</html>

merotodo-master/app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

merotodo-master/app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

merotodo-master/app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

merotodo-master/app/views/lists/index.html.erb
<section>
	<h1>Kaam</h1>
	<p>
		<div id="button">
			<%= link_to "Add kaam", new_list_path %><br/>
		</div>
		<%@lists.each do |list|%>
			<table>
				<tr>
					<td><h2>Title : </h2></td>
					<td><%=list.title%></td>
				</tr>
				<tr>
					<td><h2>Description : </h2></td>
					<td> <%=list.description%></td>
				</tr>
			</table>
			<menu>
				<ul>
					<li><%= link_to "Delete", list_path(list.id),method: :delete, data: {confirm: "Are you sure"}%></li>
					<li><%= link_to "Add items", new_list_item_path(list)%></li>
					<li><%= link_to "View items",list_items_path(list) %></li>
				</ul>
			</menu>
		<%end%>	
</section>

merotodo-master/app/views/lists/new.html.erb
<section>
	<h1>Kaam list</h1>
	<%=form_for @list do |f|%>
		<p>
			<%= f.label :title%>
			<%= f.text_field :title, placeholder: "Enter the kaam title"%>
		</p>
		<p>
			<%= f.label :description%>
			<%= f.text_area :description%>
		</p>
		<%= submit_tag ("Create kaam")%><br/>
		<%= link_to "Back", lists_path %>
	<%end%>
</section>

merotodo-master/app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>